#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Hubs,  S2, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S3,     infrared,        sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     touch,          sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     left1,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     right1,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     left2,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     right2,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     lift1,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     lift2,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     sweep,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     flag,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    bucket,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    pin,                  tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

void setMovementPower(int power, int turn){
	//turn = turn * 1.5;
	/*
	int leftBrake = 1;
	int rightBrake = 1;
	if (joy1Btn(7)){
		leftBrake = 0;
		//turn = 0;
	}
	if (joy1Btn(8)){
		rightBrake = 0;
		//turn = 0;
	}
	*/
	float leftFinal = (float) (power + turn);
	float rightFinal = (float) (-power + turn);

	if (abs(leftFinal) > 100)
	{
		rightFinal *= 100 / abs(leftFinal);
		leftFinal *= 100 / abs(leftFinal);
	}
	if (abs(rightFinal) > 100)
	{
		leftFinal *= 100 / abs(rightFinal);
		rightFinal *= 100 / abs(rightFinal);
	}
	motor[left1] = leftFinal;
	motor[right1] = rightFinal;
	motor[left2] = leftFinal;
	motor[right2] = rightFinal;
}

int correctInputs(int input){
	if (abs(input) < 20)
		input = 0;
	return input * 25/32;
}


	int servoMovement = 40; //might be 63
	int servoBase = 72; //was 130, changed when the servo was replaced and recalibrated

void initializeRobot(){
	servo[bucket] = servoBase;
  setMovementPower(0,0);
  servo[pin] = 0;
}

task main()
{

	initializeRobot();

	bool isPinEngaged = false;

	short defaultPin = 0;
	short engagedPin = 28;

  while(true){

  	getJoystickSettings(joystick);

  	//movement

  	setMovementPower(correctInputs(joystick.joy1_x2), correctInputs(joystick.joy1_y1));

  	//bucket tilt servo

  	if (joy2Btn(1))
  		servo[bucket] = servoBase - servoMovement;
  	if (joy2Btn(3))
  		servo[bucket] = servoBase + servoMovement;
  	if (joy2Btn(2))
  		servo[bucket] = servoBase;

  	//sweeper motor

  	if (!joy2Btn(8) && !joy2Btn(6) && !joy2Btn(4))
  		motor[sweep] = 0;
 	 	if (joy2Btn(8))
  		motor[sweep] = 100;
  	if (joy2Btn(6))
  		motor[sweep] = -100;
  	if (joy2Btn(4))
  		motor[sweep] = -5;

  	//flag motor

		if (!joy2Btn(7) && !joy2Btn(5))
  		motor[flag] = 0;
  	if (joy2Btn(7))
  		motor[flag] = 6;
  	if (joy2Btn(5))
  		motor[flag] = 100;

		//lift motor

  	if ((!joy1Btn(5) && !joy1Btn(6))){
  		motor[lift1] = 0;
  		motor[lift2] = 0;
  	}
  	if (joy1Btn(5) && !SensorValue[touch]){
			motor[lift1] = -100;
			motor[lift2] = -100;
		}

  	if (joy1Btn(6)){
  		motor[lift1] = 100;
  		motor[lift2] = 100;
  	}

  	if (joy1Btn(8)){
  		motor[lift1] = 20;
  		motor[lift2] = 20;
  	}

  	if (joy1Btn(7) && !SensorValue[touch]){
  		motor[lift1] = -20;
  		motor[lift2] = -20;
  	}

  	//if (joy1Btn(

  	if (motor[lift1] < 0 && SensorValue[touch])
  	{
  		motor[lift1] = 0;
  		motor[lift2] = 0;
  	}

  	//Screen debugging
  	//int fjfjfjf = 0;
  	//if (SensorValue[touch])
  	//{
  	//	fjfjfjf = 1;
  	//}
  	//nxtDisplayCenteredTextLine(0, "%d", servo[bucket]);

  	//lift pin

  	if (joy1Btn(2))
  		isPinEngaged = true;
  	if (joy1Btn(3))
  		isPinEngaged = false;

  	if (isPinEngaged)
  		servo[pin] = engagedPin;
  	if (!isPinEngaged)
  		servo[pin] = defaultPin;

  }

}
