#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Hubs,  S2, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S3,     infared,        sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     touch,          sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     Left,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Right,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     Left2,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     Right2,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Lift1,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     Lift2,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     Sweep,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     Flag,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    bucket,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    pin,                  tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.



float in = 114.649682;
float deg = 14.35;
//vars used for driving
int adjust = 25;
int dir;
int leftadjust;
int rightadjust;
//other vars
short a;//used for distance
static bool rightStuck = false;
static bool leftStuck = false;
static const short checkTime = 3000;
static const short checkDistance = 50;
static long moving = 0;
static long movingBackup = 0;
static const short liftUpTime = 1700;//lift up time
static const short liftDownTime = 1300;//lift down time

void initializeRobot()
{
	servo[bucket] = 130;
	servo[pin] = 0;
}

void resetEncoders()
{
	nMotorEncoder[Left] = 0;
	nMotorEncoder[Right] = 0;
}

void move(short speed)
{
	ClearTimer(T3);
	moving = abs(nMotorEncoder[Left]);
	movingBackup = abs(nMotorEncoder[Right]);
	dir = 1;
	if (speed < 0)
		dir = -1;
	if (speed == 0)
		dir = 0;
  speed = abs(speed);
	if (abs(nMotorEncoder[Left]) > abs(nMotorEncoder[Right]))
  {
  	leftadjust = adjust;
  	rightadjust = 0;
  }
  if (abs(nMotorEncoder[Right]) > abs(nMotorEncoder[Left]))
  {
  	leftadjust = 0;
  	rightadjust = adjust;
  }

  if (time1[T3] >= checkTime){
  		if (moving+checkDistance > abs(nMotorEncoder[Left])){
  			motor[Left] = 0;
  			motor[Left2] = 0;
  			leftStuck = true;
  		}//left is stuck
  		if (movingBackup+checkDistance > abs(nMotorEncoder[Right])){
  			motor[Right] = 0;
  			motor[Right2] = 0;
  			rightStuck = true;
  		}//right is stuck
  		moving = abs(nMotorEncoder[Left]);
			movingBackup = abs(nMotorEncoder[Right]);
			ClearTimer(T3);
		}//safety catch

	if (!leftStuck){
  	motor[Left] = dir*(speed-leftadjust);
  	motor[Left2] = dir*(speed-leftadjust);
  }

  if (!rightStuck){
  	motor[Right] = dir*(speed-rightadjust);
  	motor[Right2] = dir*(speed-rightadjust);
  }
}

void turn(short speed)
{
	ClearTimer(T2);
	moving = abs(nMotorEncoder[Left]);
	movingBackup = abs(nMotorEncoder[Right]);
	dir = 1;
	if (speed < 0)
		dir = -1;
	if (speed == 0)
		dir = 0;
  speed = abs(speed);
	if (abs(nMotorEncoder[Left]) > abs(nMotorEncoder[Right]))
  {
  	leftadjust = adjust;
  	rightadjust = 0;
  }
  else
  {
  	leftadjust = 0;
  	rightadjust = adjust;
  }
  if (time1[T3] >= checkTime){
  		if (moving+checkDistance > abs(nMotorEncoder[Left])){
  			motor[Left] = 0;
  			motor[Left2] = 0;
  			leftStuck = true;
  		}//left is stuck
  		if (movingBackup+checkDistance > abs(nMotorEncoder[Right])){
  			motor[Right] = 0;
  			motor[Right2] = 0;
  			rightStuck = true;
  		}//right is stuck
  		moving = abs(nMotorEncoder[Left]);
			movingBackup = abs(nMotorEncoder[Right]);
			ClearTimer(T3);
		}//safety catch
	if (!leftStuck){
  	motor[Left] = dir*(speed-leftadjust);
  	motor[Left2] = dir*(speed-leftadjust);
  }
  if (!rightStuck){
  	motor[Right] = -dir*(speed-rightadjust);
  	motor[Right2] = -dir*(speed-rightadjust);
  }
}

void swingLeft(short speed)
{
  motor[Left] = 0;
  motor[Left2] = 0;
  motor[Right] = speed;
  motor[Right2] = speed;
}
void swingRight(short speed)
{
  motor[Left] = speed;
  motor[Left2] = speed;
  motor[Right] = 0;
  motor[Right2] = 0;
}

task main()
{
  initializeRobot();
  short waitValue = 0;
  nNxtExitClicks = 3;
  while (nNxtButtonPressed != 0 && nNxtButtonPressed != 3){
  	nxtDisplayCenteredTextLine(0, "%d milliseconds", waitValue);
  	if (nNxtButtonPressed == 1){
  		waitValue += 1000;
  		wait1Msec(325);
  	}
  	if (nNxtButtonPressed == 2){
  		waitValue -= 1000;
 			wait1Msec(300);
 		}
  	if (waitValue > 15000)
  		waitValue = 15000;
  	if (waitValue < 0)
  		waitValue = 0;
  }


  waitForStart();

  wait1Msec(waitValue);

  int ir = 0;
  resetEncoders();
  short dist1 = 17*in;
// 1st search and raise lift
  ClearTimer(T1);
  while ((abs(nMotorEncoder[Left]) < (dist1+43*in)) && ir == 0)
  {
  	move(40);
    if (time1[T1] < liftUpTime)
  	{
  		motor[Lift1] = 100;
      motor[Lift2] = 100;
    }
    else
    {
    	motor[Lift1] = 0;
      motor[Lift2] = 0;
    }
    if ((SensorValue[infared] < 5)/* || SensorValue[infared] == 5)*/ && (abs(nMotorEncoder[Left]) > dist1))
    	ir = 1;
  }
  move(0);
// finish raising lift
  while (time1[T1] < liftUpTime)
  {
  	motor[Lift1] = 100;
  	motor[Lift2] = 100;
  }
  motor[Lift1] = 0;
  motor[Lift2] = 0;
// ir not found
  if (ir == 0)
  	ir = 2;
// align
  if ( (ir == 1) && (abs(nMotorEncoder[Left]) < (dist1)))
  {
  	wait1Msec(100);
  	a = abs(nMotorEncoder[Left])+6*in;
    while (abs(nMotorEncoder[Left]) < a)
  	  move(60);
  }
  if (ir == 2)
  {
  	wait1Msec(500);
  	while (abs(nMotorEncoder[Left]) > dist1)
  	  move(-80);
  }
  move(0);
// dump cube
  servo[bucket] = 245;
  wait1Msec(1500);
  servo[bucket] = 130;
  wait10Msec(100);
// move to end of row and lower lift
  ClearTimer(T1);
  while (abs(nMotorEncoder[Left]) > (dist1-(6*in)))
  {
  	move(-100);
    if (time1[T1] < 1400)
  	{
  		motor[Lift1] = -100;
      motor[Lift2] = -100;
    }
    else
    {
    	motor[Lift1] = 0;
      motor[Lift2] = 0;
    }
  }
  move(0);
// swing 90 deg right and lower lift
  resetEncoders();
  while (abs(nMotorEncoder[Left]) < 28*in)
  {
  	swingRight(-70);
    if (time1[T1] < liftDownTime)
  	{
  		motor[Lift1] = -100;
      motor[Lift2] = -100;
    }
    else
    {
    	motor[Lift1] = 0;
      motor[Lift2] = 0;
    }
  }
  move(0);
// move infront of ramp
  resetEncoders();
  while (abs(nMotorEncoder[Left]) < 20*in)
  {
  	move(-80);
  	if (time1[T1] < liftDownTime)
  	{
  		motor[Lift1] = -100;
      motor[Lift2] = -100;
    }
    else
    {
    	motor[Lift1] = 0;
      motor[Lift2] = 0;
    }
  }
  move(0);
// turn 90deg left
  resetEncoders();
  while (abs(nMotorEncoder[Left]) < 120*deg)
  {
  	turn(-80);
  	if (time1[T1] < liftDownTime)
  	{
  		motor[Lift1] = -100;
      motor[Lift2] = -100;
    }
    else
    {
    	motor[Lift1] = 0;
      motor[Lift2] = 0;
    }
  }
  move(0);
//finish lowering lift
  while (time1[T1] < liftDownTime)
  {
  	motor[Lift1] = -100;
  	motor[Lift2] = -100;
  }
  motor[Lift1] = 0;
  motor[Lift2] = 0;
// move up ramp
  wait1Msec(500);
  resetEncoders();
  while (abs(nMotorEncoder[Left]) < 36*in)
  	move(-80);
  move(0);


}
