#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Hubs,  S2, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S3,     infrared,        sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     touch,          sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     left1,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     right1,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     left2,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     right2,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     lift1,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     lift2,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     sweep,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     flag,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    bucket,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    pin,                  tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Teleop Debugging
//All motor outputs are thrown to the NXT display
#include "JoystickDriver.c"

void setMovementPower(int power, int turn){
	//turn = turn * 1.5;
	int leftBrake = 1;
	int rightBrake = 1;
	if (joy1Btn(7)){
		leftBrake = 0;
		//turn = 0;
	}
	if (joy1Btn(8)){
		rightBrake = 0;
		//turn = 0;
	}
	float leftFinal = (float) leftBrake * (power + turn);
	float rightFinal = (float) rightBrake * (-power + turn);

	if (abs(leftFinal) > 100)
	{
		rightFinal *= 100 / abs(leftFinal);
		leftFinal *= 100 / abs(leftFinal);
	}
	if (abs(rightFinal) > 100)
	{
		leftFinal *= 100 / abs(rightFinal);
		rightFinal *= 100 / abs(rightFinal);
	}
	motor[left1] = leftFinal;
	motor[right1] = rightFinal;
	motor[left2] = leftFinal;
	motor[right2] = rightFinal;
}

int correctInputs(int input){
	if (abs(input) < 20)
		input = 0;
	return input * 25/32;
}


	//int servoMovement = 40; //might be 63
	int servoBase = 72; //was 130, reset when servo was replaced

void initializeRobot(){
	motor[lift1] = 0;
	motor[lift2] = 0;
	motor[sweep] = 0;
	motor[flag] = 0;
	servo[bucket] = servoBase;
  setMovementPower(0,0);
  servo[pin] = 0;
}

task debugger();

task main()
{

	initializeRobot();
	eraseDisplay();
	StartTask(debugger);

  while(true){

  	getJoystickSettings(joystick);

  	//movement

  	setMovementPower(correctInputs(joystick.joy1_x2), correctInputs(joystick.joy1_y1));

  	//bucket tilt servo

  	if (joy2Btn(1))
  		servo[bucket] = 32;
  	if (joy2Btn(3))
  		servo[bucket] = 112;
  	if (joy2Btn(2))
  		servo[bucket] = 72;

  	//sweeper motor

  	if (!joy2Btn(8) && !joy2Btn(6) && !joy2Btn(4))
  		motor[sweep] = 0;
 	 	if (joy2Btn(8))
  		motor[sweep] = 100;
  	if (joy2Btn(6))
  		motor[sweep] = -100;
  	if (joy2Btn(4))
  		motor[sweep] = -15;

  	//flag motor

		if (!joy2Btn(7) && !joy2Btn(5))
  		motor[flag] = 0;
  	if (joy2Btn(7))
  		motor[flag] = 6;
  	if (joy2Btn(5))
  		motor[flag] = 100;

		//lift motor

  	if ((!joy1Btn(5) && !joy1Btn(6))){
  		motor[lift1] = 0;
  		motor[lift2] = 0;
  	}
  	if (!SensorValue[touch]){
			if (joy1Btn(5)){
				motor[lift1] = -100;
				motor[lift2] = -100;
			}
		}
  	if (joy1Btn(6)){
  		motor[lift1] = 100;
  		motor[lift2] = 100;
  	}

  	if (motor[lift1] < 0 && SensorValue[touch])
  	{
  		motor[lift1] = 0;
  		motor[lift2] = 0;
  	}

  	if (joy1Btn(2))
  		servo[pin] = 28;
  	if (joy1Btn(3))
  		servo[pin] = 0;

  }

}

task debugger()
{
	while (true)
	{
		nxtDisplayCenteredTextLine(0, "Left Motors: %d", motor[left1]);
		nxtDisplayCenteredTextLine(1, "Right Motors: %d", motor[right2]);
		nxtDisplayCenteredTextLine(2, "Sweeper Motor: %d", motor[sweep]);
		nxtDisplayCenteredTextLine(3, "Flag Motor: %d", motor[flag]);
		nxtDisplayCenteredTextLine(4, "Bucket Servo: %d", servo[bucket]);
		nxtDisplayCenteredTextLine(5, "Pin Servo: %d", servo[pin]);
		nxtDisplayCenteredTextLine(6, "T: %d %d", SensorValue[touch], SensorRaw[touch]);
		nxtDisplayCenteredTextLine(7, "IR: %d %d", SensorValue[infrared], SensorRaw[infrared]);
	}
}
