#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     infared,        sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     Left,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Right,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     Lift1,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Lift2,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     Sweep,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     Flag,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    Bucket,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

float in = 114.649682;
float deg = 16;
//vars used for driving
float a = 0;
int b = 0;
int c = 0;
int d = 0;
int e = 0;
int f = 0;
int g = 20;

void initializeRobot()
{
	servo[Bucket] = 130;
}
//MOVING
void move(int power, float dist)//"+" =foward  "-" =reverse, dist is in inches
{
	b = 1;
	if (power < 0)
	{
		b = -1;
	}
	power = abs(power)-30;
	dist = abs(dist*in/3);

	nMotorEncoder[Left] = 0;
	nMotorEncoder[Right] = 0;
  while(abs(nMotorEncoder[Left]) < dist)//acceleration
  {
  	a = 30+power*(abs(nMotorEncoder[Left])/dist);
  	if (abs(nMotorEncoder[Left]) > abs(nMotorEncoder[Right]))
  	{
  		e = g;
  		f = 0;
  	}
  	else//if (abs(nMotorEncoder[Left]) < abs(nMotorEncoder[Right]))
  	{
  		e = 0;
  		f = g;
  	}
  	motor[Left] = b*(a-e);
   	motor[Right] = b*(a-f);
  }
  //nMotorEncoder[Left] = 0;
  //nMotorEncoder[Right] = 0;
  while(abs(nMotorEncoder[Left]) < 2*dist)//constant speed
  {
  	if (abs(nMotorEncoder[Left]) > abs(nMotorEncoder[Right]))
  	{
  		e = g;
  		f = 0;
  	}
  	else//if (abs(nMotorEncoder[Left]) < abs(nMotorEncoder[Right]))
  	{
  		e = 0;
  		f = g;
  	}
  	motor[Left] = b*(a-e);
   	motor[Right] = b*(a-f);
  }
  //nMotorEncoder[Left] = 0;
  //nMotorEncoder[Right] = 0;
  while(abs(nMotorEncoder[Left]) < (3*dist))//deceleration
  {
  	a = 30+power-power*((abs(nMotorEncoder[Left])-2*dist)/dist);
  	if (abs(nMotorEncoder[Left]) > abs(nMotorEncoder[Right]))
  	{
  		e = g;
  		f = 0;
  	}
  	else//if (abs(nMotorEncoder[Left]) < abs(nMotorEncoder[Right]))
  	{
  		e = 0;
  		f = g;
  	}
  	motor[Left] = b*(a-e);
   	motor[Right] = b*(a-f);
  }
  motor[Left] = 0;
  motor[Right] = 0;
}
//TURNING
void turn(int power, float dist)// "+" =left  "-" =right, dist is in inches
{
	c = 1;
	d = -1;
	if (power < 0)
	{
		c = -1;
	  d = 1;
	}
	power = abs(power)-30;
	dist = abs(dist*deg/3);

	nMotorEncoder[Left] = 0;
	nMotorEncoder[Right] = 0;
  while(abs(nMotorEncoder[Left]) < dist)//acceleration
  {
  	a = 30+power*(abs(nMotorEncoder[Left])/dist);
  	if (abs(nMotorEncoder[Left]) > abs(nMotorEncoder[Right]))
  	{
  		e = g;
  		f = 0;
  	}
  	if (abs(nMotorEncoder[Left]) < abs(nMotorEncoder[Right]))
  	{
  		e = 0;
  		f = g;
  	}
  	motor[Left] = c*(a-e);
   	motor[Right] = d*(a-f);
  }
  //nMotorEncoder[Left] = 0;
  //nMotorEncoder[Right] = 0;
  while(abs(nMotorEncoder[Left]) < 2*dist)//constant speed
  {
  	if (abs(nMotorEncoder[Left]) > abs(nMotorEncoder[Right]))
  	{
  		e = g;
  		f = 0;
  	}
  	if (abs(nMotorEncoder[Left]) < abs(nMotorEncoder[Right]))
  	{
  		e = 0;
  		f = g;
  	}
  	motor[Left] = c*(a-e);
   	motor[Right] = d*(a-f);
  }
  //nMotorEncoder[Left] = 0;
  //nMotorEncoder[Right] = 0;
  while(abs(nMotorEncoder[Left]) < 3*dist)//deceleration
  {
  	a = 30+power-power*((abs(nMotorEncoder[Left])-2*dist)/dist);
  	if (abs(nMotorEncoder[Left]) > abs(nMotorEncoder[Right]))
  	{
  		e = g;
  		f = 0;
  	}
  	if (abs(nMotorEncoder[Left]) < abs(nMotorEncoder[Right]))
  	{
  		e = 0;
  		f = g;
  	}
  	motor[Left] = c*(a-e);
   	motor[Right] = d*(a-f);
  }
  motor[Left] = 0;
  motor[Right] = 0;
}


task main()
{
  initializeRobot();

  waitForStart();

  int ir = 0;
  int wait = 800;

  move(50,60);
/*
  //start beacon 1
  move(-100,18);//line up with beacon 1
  wait1Msec(wait);
  if (SensorValue[infared] == 5)//check for beacon 1
  {
    ir = 1;//beacon is on goal 1
  }
  if (ir == 0)//check beacon 2
  {
    move(-100,10);//line up with beacon 2
    wait1Msec(wait);
    if (SensorValue[infared] == 5)//check for beacon 2
    {
      ir = 2;//beacon is on goal 2
    }
  }
  if (ir == 0)//start beacon 3
  {
    move(-100,23);//line up with beacon 3
    wait1Msec(wait);
    if (SensorValue[infared] == 5)//check for beacon 3
    {
      ir = 3;//beacon is on goal 3
    }
  }
  if (ir == 0)//start beacon 4
  {
    move(-100,10);//line up with beacon 4
    wait1Msec(wait);
    if (SensorValue[infared] == 5)//check for beacon 4
    {
      ir = 4;//beacon is on goal 4
    }
  }

  //align with goal
  //goal 3 and 4 are already aligned
  if (ir == 1 || ir == 2)//align 1 or 2
  {
  	move(-40,2);
  }
  if (ir == 0)//if ir was not found, align with goal 1
  {
    move(100,39);
  }
  wait1Msec(wait);

  //dump cube
  motor[Lift1] = 100;
  motor[Lift2] = 100;
  wait1Msec(1500);
  motor[Lift1] = 0;
  motor[Lift2] = 0;
  wait10Msec(5);
  servo[Bucket] = 230;
  wait1Msec(1000);
  servo[Bucket] = 125;
  wait10Msec(100);
  motor[Lift1] = -100;
  motor[Lift2] = -100;
  wait1Msec(1000);
  motor[Lift1] = 0;
  motor[Lift2] = 0;

  //back up, center 18in away from end of pendulum, starting side
  if (ir == 0 || ir == 1)
  {
    move(100,22.5);
  }
  if (ir == 2)
  {
    move(100,32.5);
  }
  if (ir == 3)
  {
    move(100,51.5);
  }
  if (ir == 4)
  {
    move(100,61.5);
  }
  wait1Msec(wait);

  turn(-100,90);//turn right 90deg
  wait1Msec(wait);

  move(100,32);//move infront of ramp
  wait1Msec(wait);

  turn(100,90);//turn so back faces ramp
  wait1Msec(wait);

  move(-100,34);//drive up ramp
  wait1Msec(wait);
*/
}
