#pragma config(Sensor, S3,     infrared,        sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S1,     color,          sensorCOLORFULL)
#pragma config(Sensor, S2,     ,               sensorCOLORFULL)
#pragma config(Motor,  motorC,          light,         tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
  nxtDisplayCenteredTextLine(0,"%d", SensorValue[infrared]);
  wait10Msec(100);
}



}
