#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     infrared,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     leftFront,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     rightFront,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     bucketRaise,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     unknown,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     sweeperArm,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     flagRaise,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    bucket,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Somebody's going to read our comments at some point and wonder what the hell we even did at these meetings...
//I, for one, am currently eating Doritos. (This is Zach, not Daniel)
//Seraphina is not glaring at her phone; she is on Snapchat.

#include "JoystickDriver.c"

void setMovementPower_normal(int power, int turn){
	//int over100 = 0;
	//if (-power - turn < -100){
	//	(-power - turn)
	motor[leftFront] = -power - turn;
	motor[rightFront] = power - turn;
	return;
}

void setMovementPower_tankStyle(int leftPower, int rightPower){
	motor[leftFront] = -leftPower;
	motor[rightFront] = rightPower;
}

int correctInputs(int input){
	if (abs(input) < 25)
		input = 0;
	return input;
}

void initializeRobot(){
	servo[bucket] = 130;
  setMovementPower_normal(0,0);
}

task main()
{

	bool tankDriving = false;
	int bucketServoPos = 130;

	initializeRobot();

  while(true){

  	getJoystickSettings(joystick);

  	if(joy1Btn(9)){
  		tankDriving = false;
  	}
  	if(joy1Btn(10)){
  		tankDriving = true;
  	}

  	if(tankDriving){
  		setMovementPower_tankStyle(correctInputs(joystick.joy1_y1) * 4/5, correctInputs(joystick.joy1_y2) * 4/5);
		}
		if(!tankDriving){
			setMovementPower_normal(correctInputs(joystick.joy1_y1) * 4/5, correctInputs(joystick.joy1_x2) * 4/5);
		}

  	//time-out (for lines of code that have been naughty)
  	bucketServoPos = bucketServoPos + (correctInputs(joystick.joy2_x1) / 25.5);

  	if (bucketServoPos > 230) //controls the servo that buckets the blocky thingy (not Minecraft-related)
  		bucketServoPos = 230;
  	if (bucketServoPos < 40)
  		bucketServoPos = 40;
  	if (servo[bucket] != bucketServoPos)
  		servo[bucket] = bucketServoPos;
  	if (joy2Btn(1)){
  		bucketServoPos = 125;
  	}

  	if (!joy2Btn(2) && !joy2Btn(4)) //controls sweeping motor
  		motor[sweeperArm] = 0;
 	 	if (joy2Btn(2))
  		motor[sweeperArm] = 100;
  	if (joy2Btn(4))
  		motor[sweeperArm] = -100;

		if (!joy2Btn(3) && !joy2Btn(7) && !joy2Btn(8)) //controls flag motor
  		motor[flagRaise] = 0;
  	if (joy2Btn(8))
  		motor[flagRaise] = 5;
  	if (joy2Btn(7))
  		motor[flagRaise] = 100;
  	if (joy2Btn(3))
  		motor[flagRaise] = -5;

  	if (!joy1Btn(5) && !joy1Btn(6) && !joy1Btn(7) && !joy1Btn(8))//controls bucket lift motor
  		motor[bucketRaise] = 0;
  	if (joy1Btn(5))
  		motor[bucketRaise] = -100;
  	if (joy1Btn(6))
  		motor[bucketRaise] = 100;
  	if (joy1Btn(7))
  		motor[bucketRaise] = -15;
  	if (joy1Btn(8))
  		motor[bucketRaise] = 65;

  }

}

//Extra comments
 	//Line 154 on 11-15-13:
		//Daniel: we might want to see if we could get it to read multiple buttons at once (never mind, we can't).

  	//Zach to Daniel: that comment is wrong. You can read more than one button by using the && (and) and || (or) operators.
  	//I already fixed your code to reflect this.
  	//I also changed all instances of "if joy1Btn(n) != true" to "if !joy1Btn(n)"
		//I have no idea what I'm doing
