#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Hubs,  S2, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S3,     infrared,        sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     touch,          sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     left1,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     right1,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     left2,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     right2,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     lift1,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     lift2,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     sweep,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     flag,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    bucket,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    pin,                  tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

int servoMovement = 40; //might be 63
int servoBase = 72; //was 130, changed when the servo was replaced and recalibrated
bool gotIt  = false;

task main()
{
	while (!gotIt){
		servo[bucket] = servoBase;
		wait1Msec(500);
		nxtDisplayCenteredTextLine(0, "%d", servoBase);
		wait1Msec(500);
		while (!nNxtButtonPressed == 3){
			nxtDisplayCenteredTextLine(0, "%d", servoBase);
			if(nNxtButtonPressed == 2)
				servoBase -= 1;
			if(nNxtButtonPressed == 1)
				servoBase += 1;
		}
		while (!nNxtButtonPressed == 3){
			nxtDisplayCenteredTextLine(1, "Got it?");
			if (nNxtButtonPressed == 2)
				gotIt = false;
			else if (nNxtButtonPressed == 1)
				gotIt = true;
		}
		nxtDisplayCenteredTextLine(0, "%d", servoBase);
	}
	while (true){
		nxtDisplayCenteredTextLine(0, "%d", servoBase);
	}



}
