#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)//DON'T YOU COPY THESE CONFIGS
#pragma config(Hubs,  S2, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S3,     infared,        sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     touch,          sensorTouch)//I KNOW YOU WANT TO
#pragma config(Motor,  mtr_S1_C1_1,     Left,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Right,         tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     Left2,         tmotorTetrix, openLoop, reversed)//DON'T DO IT
#pragma config(Motor,  mtr_S1_C3_2,     Right2,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Lift1,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     Lift2,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     Sweep,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     Flag,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    bucket,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    pin,                  tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//NEVER EVER COPY THE CONFIGS FROM THIS PROGRAM
//EVER
//If YOU NEED CONFIGS, GET THEM FROM DRIVENOACCEL
//NOT THIS
//I CANNOT EMPHASIZE THIS ENOUGH

//version 6.0.1 alpha

#include "JoystickDriver.c"

void setMovementPower_normal(int power, int turn){
	int a = 1;
	int b = 1;
	if (joy1Btn(7))
		a = 0;
	if (joy1Btn(8))
		b = 0;
	motor[Left2] = a*(power + turn);
	motor[Right2] = b*(power - turn);
	motor[Left] = a*(power + turn);
	motor[Right] = b*(power - turn);
}

void setMovementPower(int power, int turn){
	short leftBrake = 1;
	short rightBrake = 1;
	float largest;
	float leftFinal = (float) power + turn;
	float rightFinal = (float) power + turn;
	if (leftFinal > 100 && rightFinal <= 100){
		float correction = 100/leftFinal;
		leftFinal = 100;
		rightFinal *= correction;
	}
	if (rightFinal > 100 && leftFinal <= 100){
		float correction = 100/rightFinal;
		rightFinal = 100;
		leftFinal *= correction;
	}
	if (rightFinal > 100 && leftFinal > 100){
		if (leftFinal > rightFinal){
			float largest = leftFinal;
		}
		else{
			float largest = rightFinal;
		}
		float correction = 100/largest;
		rightFinal *= correction;
		leftFinal *= correction;
	}
	if (joy1Btn(7)){
		leftBrake = 0;
	}
	if (joy1Btn(8)){
		rightBrake = 0;
	}

	motor[Left] = leftBrake * leftFinal;
	motor[Left2] = leftBrake * leftFinal;
	motor[Right] = rightBrake * rightFinal;
	motor[Right2] = rightBrake * rightFinal;

}

int correctInputs(int input){
	if (abs(input) < 30)
		input = 0;
	return input;
}

void initializeRobot(){
	servo[bucket] = 135;
  setMovementPower_normal(0,0);
  servo[pin] = 0;
}

task main()
{

	initializeRobot();
	short servoMovement = 40; //might be 63

  while(true){

  	getJoystickSettings(joystick);

  	setMovementPower(correctInputs(joystick.joy1_y1) * 4/5, correctInputs(joystick.joy1_x2) * 4/5);
  	if (joy2Btn(1))//this tilts the bucket to the blue side
  		servo[bucket] = 135-servoMovement;
  	if (joy2Btn(3))//this tilts the bucket to the red side
  		servo[bucket] = 135+servoMovement;
  	if (joy2Btn(2))
  		servo[bucket] = 135;

  	if (!joy2Btn(8) && !joy2Btn(6) && !joy2Btn(4)) //controls sweeping motor
  		motor[Sweep] = 0;
 	 	if (joy2Btn(8))
  		motor[Sweep] = 100;
  	if (joy2Btn(6))
  		motor[Sweep] = -100;
  	if (joy2Btn(4))
  		motor[Sweep] = -5;

		if (!joy2Btn(7) && !joy2Btn(5)) //controls flag motor
  		motor[Flag] = 0;
  	if (joy2Btn(7))
  		motor[Flag] = 6;
  	if (joy2Btn(5))
  		motor[Flag] = 100;

  	if (!joy1Btn(5) && !joy1Btn(6)){//controls bucket lift motor
  		motor[Lift1] = 0;
  		motor[Lift2] = 0;
  	}
		if (joy1Btn(5)){
			motor[Lift1] = -100;
			motor[Lift2] = -100;
		}

  	if (SensorValue[touch]){
  		if (joy1Btn(5)){
  			motor[Lift1] = 0;
  			motor[Lift2] = 0;
  		}
  	}

  	if (joy1Btn(6)){
  		motor[Lift1] = 100;
  		motor[Lift2] = 100;
  	}
  	if (joy1Btn(2))
  		servo[pin] = 28;
  	if (joy1Btn(3))
  		servo[pin] = 0;

  }

}

/*
Official Button Map:
Controller 1:
	Left Joystick forward/backward controls forward/backward movement
	Right Joystick side-to-side controls rotation if left joystick is not engaged, and curvature of a turn if left joystick is engaged.
	Left Trigger sets all left motors to zero, so that the robot turns left about its side
	Right Trigger sets all right motors to zero, so that the robot turns right about its side
	Right Bumper sets both lift motors to full upwards power
	Left Bumper sets both lift motors to full downwards power
	Lower button locks the lift using the pin
	Middle Right button resets the pin
*/
