#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S3,     infared,        sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     Left,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Right,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     Lift1,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Lift2,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     Sweep,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     Flag,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    bucket,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

float in = 114.649682;

//float a = 0; //just a var, used in AutoIR_rev 2


void initializeRobot()
{
	servo[bucket] = 130;
}

void accelerate(int maxSpeed, int timeToSpeed, int startSpeed, int maxDistance)
{
	maxDistance = maxDistance*in;
	int i = 0;//this will be used for the time to full speed in msec)
	int currentSpeed = startSpeed;
	motor[Left] = startSpeed;
	motor[Right] = startSpeed;
	while (i < timeToSpeed){
		if ((currentSpeed + (maxSpeed/100)) >= maxSpeed){
			motor[Left] = maxSpeed;
			motor[Right] = maxSpeed;
			i = timeToSpeed;
		}
		if ((currentSpeed + (maxSpeed/100)) < maxSpeed){
			currentSpeed += (maxSpeed/100);
			motor[Left] = currentSpeed;
			motor[Right] = currentSpeed;
			wait1Msec(timeToSpeed/100);
			i += (timeToSpeed/100);
		}
		if (maxDistance <= abs(nMotorEncoder[Left]))
			i = timeToSpeed;
	}
	while (maxDistance > abs(nMotorEncoder[Left])){
		motor[Left] = maxSpeed;
		motor[Right] = maxSpeed;
	}
}
void decelerate(int minSpeed, int timeToSpeed, int startSpeed, int maxDistance)
{
	int j = 0;//this is the time to speed as a variable
	int currentSpeed = startSpeed;
	motor[Left] = startSpeed;
	motor[Right] = startSpeed;
	while (j < timeToSpeed){
		if ((currentSpeed - ((100 - minSpeed)/100)) >= (100 - minSpeed)){
			motor[Left] = minSpeed;
			motor[Right] = minSpeed;
			j = timeToSpeed;
		}
		if ((currentSpeed + ((100 - minSpeed/100))) < (100 - minSpeed)){
			currentSpeed += (100 - minSpeed);
			motor[Left] = currentSpeed;
			motor[Right] = currentSpeed;
			wait1Msec(timeToSpeed);
			j += (timeToSpeed/100);
		}
		if (maxDistance <= abs(nMotorEncoder[Left])){
			motor[Left] = minSpeed;
			motor[Right] = minSpeed;
			j = timeToSpeed;
		}
	}
	while (maxDistance > abs(nMotorEncoder[Left])){
		motor[Left] = ((startSpeed/abs(startSpeed)*25));
		motor[Right] = ((startSpeed/abs(startSpeed)*25));
	}
	motor[Left] = minSpeed;
	motor[Right] = minSpeed;
}

task main()
{
	initializeRobot();

  waitForStart();
  int speed = 100;//speed of robot while moving, changes after dump cube


  //go onto the ramp.
  nMotorEncoder[Left] = 0;
  accelerate(speed, 1000, 0, 55);
  decelerate(0, 250, speed, 5);
}
