#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Hubs,  S2, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     infrared,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     touch,          sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     Left,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Right,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     Lift1,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     Lift2,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     Left2,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     Right2,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     Sweep,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     Flag,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    bucket,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    pin,                  tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//version 6.0.1 alpha

#include "JoystickDriver.c"


#ifndef NXTBUTTONPRESS
#define NXTBUTTONPRESS 325
#endif
#ifndef PI
#define PI 3.14159265358979323846246
#endif
//#ifndef TURN90TIME
//static const int TURN90TIME = 535;
//#endif
//#ifndef TURN45TIME
//static const int TURN45TIME = 350;
//#endif

bool testing = false;
bool defend_ramp = false;

//Up ramp time
static const int UPRAMPTIME = 2000;
static const int UPRAMPDIST = 27;
//static const short delay = 0;//set this number to the delay in seconds ***(SET IN GUI (DANIEL))***

//initializing all procedures that are used (***(Actually called prototyping, not initializing (Daniel))***)
static void resetEncoders();
static void initializeRobot();
static void move(int speed);
static void moveForward(float power);
static void dumpCube();
static void turn(float power); //right is positive, left is negative
static void turn90(bool right);//true is right, false is left
static void turn45(bool right);//true is right, false is left
static void newturn45(bool right);
static void swingLeft(bool forward);//true is forward, false is backward

void brake(int waitTime = 0){
	ClearTimer(T3);
	move(0);
	wait1Msec(waitTime*1000);

}

void pauseForTest(){
	brake();
	while (!nNxtButtonPressed == 3){
		wait1Msec(10);
	}
}

//initializing all functions that are used ***Prototyping, not initializing (Daniel)***
static float distanceTravelled();
static float encoderDifference();
bool matchHasStarted = false;

//for the move function
int adjust = 20;
int dir;
int leftadjust;
int rightadjust;

//initializing all tasks that are used ***Prototyping, for the third time (Daniel)***
task nxtDebugger();
task liftUp();
task liftDown();
task waitUntilStart();

//initializing all the global integers that are used ***this is initializing (Daniel)***
static const unsigned short liftUpTime = 2050;
static const unsigned short liftDownTime = 1300;
//static const short swingTime = 890;
static short power;
static const unsigned short rampLineUpDistance = 25;

//initializing all the global floats that are used
static const float in = 360/PI;
static float distToBucket;

//initializing all the global booleans that are used
bool liftedUp = false;
bool foundCrate = false;
bool liftIsDown = false;

//initializing all the arrays that are used
static const float irDistances[4] = {16.5, 10, 18.5, 10}; //do not change this list without updating irBackDistances[]
//static const float irBackDistances[4] = {irDistances[0]-7, irBackDistances[0]+irDistances[1], irBackDistances[1]+irDistances[2], irBackDistances[2]+irDistances[3]}; //***five inches off of the TOTAL DISTANCE TRAVELLED, !!!NOT TWO INCHES LESS THAN irDistances!!! (Daniel)***
// The line above this is replaced by the line below this comment, and the assignments are replaced by a for loop inside the task main
static float irBackDistances[4] = {irDistances[0]-7,-4,0,-3.5};
static const short irValues[4] = {4, 4, 5, 5};

static short crateVal = 0;//initializes the value that will be set to the crate which has the IR beacon

task main(){

	for(int i = 1; i <= 3; i++)
	{
		irBackDistances[i] += irDistances + irBackDistances[i-1];
	}

	//This is for the nxt GUI
  nNxtExitClicks = 3;
  static int delay = 0;
  static int i;

  StartTask(waitUntilStart);
  //This next section of code is a nxt delay setting gui, please do not mess this up, also...
  ///***********************PRESS THE ORANGE BUTTON!!!!**********************
  while (nNxtButtonPressed != 3 && !matchHasStarted){
  	if (nNxtButtonPressed == 1)
  		delay += 1;
  	if (nNxtButtonPressed == 2)
  		delay -= 1;
  	/*
  	if (delay > 15)
  		delay = 0;
  	if (delay < 0)
  		delay = 15;
  		*/
  	if (nNxtButtonPressed == 0)
  	{
  		if (delay != 0)
  			i = 0;
  		else
  			i = 15;
  		delay = i;
  	}

  	nxtDisplayCenteredTextLine(0, "%2.2f second delay", delay);
  	wait1Msec(NXTBUTTONPRESS);

  }
  eraseDisplay();
  StartTask(nxtDebugger);

  while (!matchHasStarted)
  {
  	wait1Msec(1);
  }

  StopTask(waitUntilStart);

	resetEncoders();//sets the wheel encoders to zero
	initializeRobot();//initializes the robot

	waitForStart();//waits until the start signal

	ClearTimer(T1);//Used for the countering pushes at the end

	wait1Msec(delay*1000);//waits the number of seconds set by the program

	move(30);//starts moving backwards

	StartTask(liftUp);//start moving the lift up while the program runs

	for (short currentCrate = 0; currentCrate < 4; currentCrate++){//runs through the next block four times or until it finds the beacon
		while (distanceTravelled() <= irDistances[currentCrate]-1){move(30);}//waits until the robot is at each bucket
		if (testing)
			brake(5);
		if (currentCrate == 2)
			brake(1);
		for (short i=0; i<10; i++){
			if (SensorValue(infrared) == irValues[currentCrate]){//checks to see if the robot is at the bucket with the beacon
				foundCrate = true;
				crateVal = currentCrate+1;//sets the global variable that shows the rest of the program where the beacon is
				brake();//stops the robot
				wait1Msec(250);//slight delay (to lose momentum and completely stop)
				distToBucket = distanceTravelled();
				currentCrate = 4;
				i = 10;
				continue;
			}
			wait10Msec(1);
		}
		if (crateVal != 0){
			currentCrate = 4;
			continue;
		}
		resetEncoders();//resets the encoders after every basket
	}

	resetEncoders();//resets the encoders again (to confirm that they were reset when the for loop broke)
	brake();//stops the robot in case the first one didn't work

	if (!foundCrate || crateVal == 0)//runs through if the sensor did not find the beacon
		crateVal = 4;//the robot is at the fourth bucket if it did not find the beacon anywhere else

	while (!liftedUp){}//waits if the lift is not all the way up yet
	StopTask(liftUp);//stops the task after the lift is up

	dumpCube();//dumps the cube
	//wait1Msec(1000);//pointless
	StartTask(liftDown);//starts dropping the lift

	move(-60);//moves forward towards the starting position

	while (distanceTravelled() <= irBackDistances[crateVal-1]){move(-60);}//waits until the robot is five inches away from the wall

	brake();//stops five inches away from the wall
	//resetEncoders();
	resetEncoders();
	wait1Msec(800);
	turn45(false);//turns right at half power
	wait1Msec(800);

	resetEncoders();
	move(-60);
	while (distanceTravelled() < 12){move(-60);}

	brake();
	wait1Msec(800);
	resetEncoders();
	turn45(false);
	wait1Msec(800);
	resetEncoders();
	move(-60);
	while (distanceTravelled() < rampLineUpDistance){move(-60);}
	brake();

	while (!liftIsDown){}
	StopTask(liftDown);

	wait1Msec(800);
	resetEncoders();
	turn90(false);//turns right at half power

	wait1Msec(800);

	ClearTimer(T4);
	resetEncoders();
	moveForward(-100);
	while(distanceTravelled() <= UPRAMPDIST && time1[T4] <= UPRAMPTIME){wait1Msec(1);}
	brake();

	if (defend_ramp)
	{
		brake();
		wait1Msec(100);
		turn90(true);
		brake();
		moveForward(-100);
		wait1Msec(500);
		brake();
	}
/* //**OLD RAMP DEFENSE CODE: DO NOT USE UNLESS CIRCUMSTANCES ARE DIRE**
	brake();
	wait1Msec(100);
	swingLeft(false);
	wait1Msec(swingTime);
	brake();
	moveForward(-100);
	wait1Msec(500);
	brake();
	*/
	resetEncoders();//This  following loop counters any pushes that the robot may encounter
	//int currentCheck = 0;
	while (true){ //condition was "time1[T1] < 29500"; changed by Zach. It will continue to run until the field stops automatically.
		if ((nMotorEncoder[Left]+nMotorEncoder[Right])/2 <= -0.5*in && (nMotorEncoder[Left]+nMotorEncoder[Right])/2 > -2*in){
			moveForward(30);
		}
		if ((nMotorEncoder[Left]+nMotorEncoder[Right])/2 >= 0.5*in && (nMotorEncoder[Left]+nMotorEncoder[Right])/2 < 2*in){
			moveForward(-30);
		}
		if ((nMotorEncoder[Left]+nMotorEncoder[Right])/2 >= 2*in){
			moveForward(-100);
		}
		if ((nMotorEncoder[Left]+nMotorEncoder[Right])/2 <= -2*in){
			moveForward(100);
		}
		if ((nMotorEncoder[Left]+nMotorEncoder[Right])/2 > -0.5*in){
			if ((nMotorEncoder[Left]+nMotorEncoder[Right])/2 < 0.5*in){
				brake();
			}
		}
	}
	//the following two lines of code will never be executed
	brake();
	initializeRobot();
}

task waitUntilStart()
{
	waitForStart();
	matchHasStarted = true;
}


task nxtDebugger(){
	while (true){
		nxtDisplayCenteredTextLine(0, "%d", distanceTravelled());
		nxtDisplayCenteredTextLine(1, "%d", nMotorEncoder[Left]);
		nxtDisplayCenteredTextLine(2, "%d", nMotorEncoder[Right]);
		nxtDisplayCenteredTextLine(3, "%d", SensorValue[infrared]);
		nxtDisplayCenteredTextLine(4, "%d", crateVal);
		wait1Msec(10);
	}
	EndTimeSlice();
}

task liftUp(){
	motor[Lift1] = 100;
	motor[Lift2] = 100;
	wait1Msec(liftUpTime);

	motor[Lift1] = 0;
	motor[Lift2] = 0;
	liftedUp = true;

	EndTimeSlice();
}

task liftDown(){
	motor[Lift1] = -100;
	motor[Lift2] = -100;
	wait1Msec(liftDownTime);

	motor[Lift1] = 0;
	motor[Lift2] = 0;
	liftIsDown = true;

	EndTimeSlice();
}

void resetEncoders(){
	nMotorEncoder[Left] = 0;
	nMotorEncoder[Right] = 0;
}

void initializeRobot(){
	resetEncoders();
	brake();
	motor[Lift1] = 0;
	motor[Lift2] = 0;
	motor[Sweep] = 0;
	motor[Flag] = 0;
	servo[bucket] = 102;
	servo[pin] = 0;
}

void move(int speed)
{
	dir = 1;
	if (speed < 0)
		dir = -1;
	if (speed == 0)
		dir = 0;
  speed = abs(speed);
	if (abs(nMotorEncoder[Left]) > abs(nMotorEncoder[Right]))
  {
  	leftadjust = adjust;
  	rightadjust = 0;
  }
  else
  {
  	leftadjust = 0;
  	rightadjust = adjust;
  }
  motor[Left] = dir*(speed-leftadjust);
  motor[Left2] = dir*(speed-leftadjust);
  motor[Right] = dir*(speed-rightadjust);
  motor[Right2] = dir*(speed-rightadjust);
}

void moveForward(float power){
	motor[Left] = power;
	motor[Left2] = power;
	motor[Right] = power;
	motor[Right2] = power;
}

void adjust12(){
	moveForward(25);
	while (distanceTravelled() <= 2){}
	brake();
}

void adjust34(){
	moveForward(-25);
	while (distanceTravelled() <= 2){}
	brake();
}

void dumpCube(){
	int servoMovement = 40;
	wait1Msec(50);
	servo[bucket] = 102;
	wait1Msec(50);
	servo[bucket] = 102 + (servoMovement);
	wait1Msec(2000);
	servo[bucket] = 102;
	wait1Msec(50);
}

void turn(float power){ //right is positive, left is negative
	motor[Left] = power;
	motor[Left2] = power;
	motor[Right] = -power;
	motor[Right2] = -power;
}

void turn90(bool right){ //true is right, false is left
	/*
	if (right)
		power = 100;
	if (!right)
		power = -100;
	motor[Left] = power;
	motor[Left2] = power;
	motor[Right] = -power;
	motor[Right2] = -power;
	wait1Msec(TURN90TIME);
	brake();
	*/
	turn45(right);
	turn45(right);
}

/*void turn45(bool right){ //true is right, false is left
	if (right)
		power = 100;
	if (!right)
		power = -100;
	motor[Left] = power;
	motor[Left2] = power;
	motor[Right] = -power;
	motor[Right2] = -power;
	wait1Msec(TURN45TIME);
	brake();
}*/

//***************************WILL ONLY WORK FOR RIGHT TURNS**********************************
void turn45(bool right){ //true is right, false is left
	if (right){
		power = 100;
	}
	else{
		power = -100;
	}
	resetEncoders();
	motor[Left] = power;
	motor[Left2] = power;
	motor[Right] = -power;
	motor[Right2] = -power;
	//wait1Msec(TURN45TIME);
	while ((abs(nMotorEncoder[Left]) + abs(nMotorEncoder[Right]))/2 < 645)
		wait1Msec(1);
	brake();
}

float turn45Num(){
	return ((abs(nMotorEncoder[Left]-885)+abs(nMotorEncoder[Right]+447))/2);
}

void newturn45(bool right){
	if (right)
		power = 100;
	if (!right)
		power = -100;
	motor[Left] = power;
	motor[Left2] = power;
	motor[Right] = -power;
	motor[Right2] = -power;
	while (turn45Num() <= 10){
		wait1Msec(1);
	}
	brake();
}
void swingLeft(bool forward){
	short direction = 1;
	if (!forward)
		direction = -1;
	motor[Left] = 100*direction;
	motor[Left2] = 100*direction;
}

float distanceTravelled(){
	return((abs(nMotorEncoder[Left]+nMotorEncoder[Right])/2)/in);
}

float encoderDifference(){
	float left = nMotorEncoder[Left];
	float right = nMotorEncoder[Right];
	return(abs(left-right));
}
