#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Hubs,  S2, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S3,     infared,        sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     touch,          sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     Left,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Right,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     Left2,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     Right2,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Lift1,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     Lift2,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     Sweep,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     Flag,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    bucket,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    pin,                  tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


//version 5.0.0 alpha

#include "JoystickDriver.c"

void setMovementPower(int power, int turn){
	if (power != 0)
	{
		turn = turn * 1.5;
	}
	int leftBreak = 1;
	int rightBreak = 1;
	if (joy1Btn(7)){
		leftBreak = 0;
		turn = 0;
	}
	if (joy1Btn(8)){
		rightBreak = 0;
		turn = 0;
	}
	int leftFinal = leftBreak * (power + turn);
	int rightFinal = rightBreak * (power - turn);

	if (abs(leftFinal) > 100)
	{
		rightFinal = rightFinal * (100 / abs(leftFinal));
		leftFinal = leftFinal * (100 / abs(leftFinal));
	}
	if (abs(rightFinal) > 100)
	{
		leftFinal = leftFinal * (100 / abs(rightFinal));
		rightFinal = rightFinal * (100 / abs(rightFinal));
	}
	motor[Left2] = leftFinal;
	motor[Right2] = rightFinal;
	motor[Left] = leftFinal;
	motor[Right] = rightFinal;
}

int correctInputs(int input){
	if (abs(input) < 30)
		input = 0;
	return input * 25/32;
}

void initializeRobot(){
	servo[bucket] = 135;
  setMovementPower(0,0);
  servo[pin] = 0;
}

task main()
{

	initializeRobot();
	int servoMovement = 40; //might be 63


  while(true){

  	getJoystickSettings(joystick);

  	//movement

  	setMovementPower(correctInputs(joystick.joy1_y1), correctInputs(joystick.joy1_x2));

  	//bucket tilt servo

  	if (joy2Btn(1))
  		servo[bucket] = 135 - servoMovement;
  	if (joy2Btn(3))
  		servo[bucket] = 135 + servoMovement;
  	if (joy2Btn(2))
  		servo[bucket] = 135;

  	//sweeper motor

  	if (!joy2Btn(8) && !joy2Btn(6) && !joy2Btn(4))
  		motor[Sweep] = 0;
 	 	if (joy2Btn(8))
  		motor[Sweep] = 100;
  	if (joy2Btn(6))
  		motor[Sweep] = -100;
  	if (joy2Btn(4))
  		motor[Sweep] = -5;

  	//flag motor

		if (!joy2Btn(7) && !joy2Btn(5))
  		motor[Flag] = 0;
  	if (joy2Btn(7))
  		motor[Flag] = 6;
  	if (joy2Btn(5))
  		motor[Flag] = 100;

		//lift motor

  	if ((!joy1Btn(5) && !joy1Btn(6)) || SensorValue[touch]){
  		motor[Lift1] = 0;
  		motor[Lift2] = 0;
  	}
		if (joy1Btn(5)){
			motor[Lift1] = -100;
			motor[Lift2] = -100;
		}
  	if (joy1Btn(6)){
  		motor[Lift1] = 100;
  		motor[Lift2] = 100;
  	}

  	//lift pin

  	if (joy1Btn(2))
  		servo[pin] = 28;
  	if (joy1Btn(3))
  		servo[pin] = 0;

  }

}
