#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Hubs,  S2, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S3,     infared,        sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     touch,          sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     Left,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Right,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     Left2,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     Right2,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Lift1,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     Lift2,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     Sweep,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     Flag,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    bucket,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    pin,                  tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth message

//Note to self: change
//Variables to change the function of the program

int dirOfBucket = 1; //1 for right, -1 for left
int waitTime = 0;
bool moveAndLift = true;//1 if the robot moves and lifts at the same time, 0 if separate.
int firstMoveTime = 1000;
int liftUpTime = 1750;


void setMovementPower(int power, int turn){
	short leftBrake = 1;
	short rightBrake = 1;
	float correction = 0;
	float largest;
	float leftFinal = (float) power + turn;
	float rightFinal = (float) power + turn;
	if (leftFinal > 100 && rightFinal <= 100){
		float correction = 100/leftFinal;
		leftFinal = 100;
		rightFinal *= correction;
	}
	if (rightFinal > 100 && leftFinal <= 100){
		float correction = 100/rightFinal;
		rightFinal = 100;
		leftFinal *= correction;
	}
	if (rightFinal > 100 && leftFinal > 100){
		if (leftFinal > rightFinal){
			float largest = leftFinal;
		}
		else{
			float largest = rightFinal;
		}
		float correction = 100/largest;
		rightFinal *= correction;
		leftFinal *= correction;
	}
	/*if (joy1Btn(7)){
		leftBrake = 0;
	}
	if (joy1Btn(8)){
		rightBrake = 0;
	}*/

	motor[Left] = leftBrake * leftFinal;
	motor[Left2] = leftBrake * leftFinal;
	motor[Right] = rightBrake * rightFinal;
	motor[Right2] = rightBrake * rightFinal;

}

void dumpCube(){
	servo[bucket] = 130;
	wat1Msec(500);
	servo[bucket] = 130 + dirOfBucket*45;
	wait1Msec(2500);


task main()
{
wait1Msec(waitTime);
ClearTimer(T1);//The timer used for the first move
ClearTimer(T2);//The timer used for the second move

bool firstMove = true;
bool liftUp = true;

while (firstMove || liftUp){
	if (time1[T1] >= firstMoveTime)
		firstMove = 0;
	if (time1[T2] >= liftUpTime)
		liftUp = 0;
	if (firstMove){
		setMovementPower(50, 0);
	}
	else{
		setMovementPower(0, 0);
	}
	if (liftUp){
		motor[Lift1] = 100;
		motor[Lift2] = 100;
	}
	else{
		motor[Lift1] = 0;
		motor[Lift2] = 0;
	}
}



}
