#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S3,     infrared,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     touch,          sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     Left,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Right,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     Lift1,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     Lift2,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     Sweep,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     Flag,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    bucket,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    pin,                  tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Somebody's going to read our comments at some point and wonder what the hell we even did at these meetings...
//I, for one, am currently eating Doritos. (This is Zach, not Daniel)
//Seraphina is not glaring at her phone; she is on Snapchat.

//version 5.0.0 alpha

#include "JoystickDriver.c"

void setMovementPower_normal(int power, int turn){
	//int over100 = 0;
	//if (-power - turn < -100){
	//	(-power - turn)
	motor[Left] = power + turn;
	motor[Right] = power - turn;
}

int correctInputs(int input){
	if (abs(input) < 30)
		input = 0;
	return input;
}

void initializeRobot(){
	servo[bucket] = 135;
  setMovementPower_normal(0,0);
  servo[pin] = 0;
}

task main()
{

	initializeRobot();

  while(true){

  	getJoystickSettings(joystick);

  	setMovementPower_normal(correctInputs(joystick.joy1_y1) * 4/5, correctInputs(joystick.joy1_x2) * 4/5);

  	//time-out (for lines of code that have been naughty)
  	/*bucketServoPos = bucketServoPos + (correctInputs(joystick.joy2_x1) / 25.5);

  	if (bucketServoPos > 230) //controls the servo that buckets the blocky thingy (not Minecraft-related)
  		bucketServoPos = 230;
  	if (bucketServoPos < 40)
  		bucketServoPos = 40;
  	if (servo[bucket] != bucketServoPos)
  		servo[bucket] = bucketServoPos;*/
  	if (joy2Btn(1))//this controlls the bucket servo
  		servo[bucket] = 10;
  	if (joy2Btn(3))
  		servo[bucket] = 245;
  	if (joy2Btn(2)){
  		servo[bucket] = 135;
  	}

  	if (!joy2Btn(8) && !joy2Btn(6) && !joy2Btn(4)) //controls sweeping motor
  		motor[Sweep] = 0;
 	 	if (joy2Btn(8))
  		motor[Sweep] = 100;
  	if (joy2Btn(6))
  		motor[Sweep] = -100;
  	if (joy2Btn(4))
  		motor[Sweep] = 5;

		if (!joy2Btn(7) && !joy2Btn(5)) //controls flag motor
  		motor[Flag] = 0;
  	if (joy2Btn(7))
  		motor[Flag] = -6;
  	if (joy2Btn(5))
  		motor[Flag] = -100;


  	if (!joy1Btn(5) && !joy1Btn(6) && !joy1Btn(7) && !joy1Btn(8)){//controls bucket lift motor
  		motor[Lift1] = 0;
  		motor[Lift2] = 0;
  	}

  	while (!SensorValue[touch]){
  		if (joy1Btn(5)){
  			motor[Lift1] = -100;
  			motor[Lift2] = -100;
  		}
  		if (joy1Btn(6)){
  			motor[Lift1] = 100;
  			motor[Lift2] = 100;
  		}
  		if (joy1Btn(7)){
  			motor[Lift1] = -50;
  			motor[Lift2] = -50;
  		}
  		if (joy1Btn(8)){
  			motor[Lift1] = 50;
  			motor[Lift2] = 50;
  		}
  	}

  	while (SensorValue[touch]){
  		motor[Lift1] = 0;
  		motor[Lift2] = 0;
  		if (joy1Btn(8)){
  			motor[Lift1] = 50;
  			motor[Lift2] = 50;
  		}
  		if (joy1Btn(6)){
  			motor[Lift1] = 100;
  			motor[Lift2] = 100;
  		}
  	}

  	if (joy1Btn(2))
  		servo[pin] = 30;
  	if (joy1Btn(3))
  		servo[pin] = 0;

  }

}

//Extra comments
 	//Line 154 on 11-15-13:
		//Daniel: we might want to see if we could get it to read multiple buttons at once (never mind, we can't).

  	//Zach to Daniel: that comment is wrong. You can read more than one button by using the && (and) and || (or) operators.
  	//I already fixed your code to reflect this.
  	//I also changed all instances of "if joy1Btn(n) != true" to "if !joy1Btn(n)"
		//I have no idea what I'm doing
