#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Hubs,  S2, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S3,     infared,        sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     touch,          sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     Left,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Right,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     Left2,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     Right2,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Lift1,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     Lift2,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     Sweep,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     Flag,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    bucket,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    pin,                  tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.



float in = 114.59155902616464175;
//float deg = 14.35;
//vars used for driving
static unsigned const short adjust = 25;
static short dir;
static short leftadjust;
static short rightadjust;
//other vars
static bool rightStuck = false;
static bool leftStuck = false;
static const short checkTime = 3000;
static const short checkDistance = 50;
static long moving = 0;
static long movingBackup = 0;
short liftUpTime = 1750;//lift up time
short liftDownTime = 1300;//lift down time

long distanceTravelled(){
	return (abs((nMotorEncoder[Left]+nMotorEncoder[Right])/2));
}
void initializeRobot()
{
	servo[bucket] = 130;
	servo[pin] = 0;
}

void resetEncoders()
{
	nMotorEncoder[Left] = 0;
	nMotorEncoder[Right] = 0;
}

void move(short speed)
{
	ClearTimer(T3);
	moving = abs(nMotorEncoder[Left]);
	movingBackup = abs(nMotorEncoder[Right]);
	dir = 1;
	if (speed < 0)
		dir = -1;
	if (speed == 0)
		dir = 0;
  speed = abs(speed);
	if (abs(nMotorEncoder[Left]) > abs(nMotorEncoder[Right]))
  {
  	leftadjust = adjust;
  	rightadjust = 0;
  }
  if (abs(nMotorEncoder[Right]) > abs(nMotorEncoder[Left]))
  {
  	leftadjust = 0;
  	rightadjust = adjust;
  }

  if (time1[T3] >= checkTime){
  		if (moving+checkDistance > abs(nMotorEncoder[Left])){
  			motor[Left] = 0;
  			motor[Left2] = 0;
  			leftStuck = true;
  		}//left is stuck
  		if (movingBackup+checkDistance > abs(nMotorEncoder[Right])){
  			motor[Right] = 0;
  			motor[Right2] = 0;
  			rightStuck = true;
  		}//right is stuck
  		moving = abs(nMotorEncoder[Left]);
			movingBackup = abs(nMotorEncoder[Right]);
			ClearTimer(T3);
		}//safety catch

	if (!leftStuck){
  	motor[Left] = dir*(speed-leftadjust);
  	motor[Left2] = dir*(speed-leftadjust);
  }

  if (!rightStuck){
  	motor[Right] = dir*(speed-rightadjust);
  	motor[Right2] = dir*(speed-rightadjust);
  }
}

void turn(short speed)
{
	ClearTimer(T2);
	moving = abs(nMotorEncoder[Left]);
	movingBackup = abs(nMotorEncoder[Right]);
	dir = 1;
	if (speed < 0)
		dir = -1;
	if (speed == 0)
		dir = 0;
  speed = abs(speed);
	if (abs(nMotorEncoder[Left]) > abs(nMotorEncoder[Right]))
  {
  	leftadjust = adjust;
  	rightadjust = 0;
  }
  else
  {
  	leftadjust = 0;
  	rightadjust = adjust;
  }
  if (time1[T3] >= checkTime){
  		if (moving+checkDistance > abs(nMotorEncoder[Left])){
  			motor[Left] = 0;
  			motor[Left2] = 0;
  			leftStuck = true;
  		}//left is stuck
  		if (movingBackup+checkDistance > abs(nMotorEncoder[Right])){
  			motor[Right] = 0;
  			motor[Right2] = 0;
  			rightStuck = true;
  		}//right is stuck
  		moving = abs(nMotorEncoder[Left]);
			movingBackup = abs(nMotorEncoder[Right]);
			ClearTimer(T3);
		}//safety catch
	if (!leftStuck){
  	motor[Left] = dir*(speed-leftadjust);
  	motor[Left2] = dir*(speed-leftadjust);
  }
  if (!rightStuck){
  	motor[Right] = -dir*(speed-rightadjust);
  	motor[Right2] = -dir*(speed-rightadjust);
  }
}

void swingLeft(short speed)
{
  motor[Left] = 0;
  motor[Left2] = 0;
  motor[Right] = speed;
  motor[Right2] = speed;
}
void swingRight(short speed)
{
  motor[Left] = speed;
  motor[Left2] = speed;
  motor[Right] = 0;
  motor[Right2] = 0;
}

task main()
{
	initializeRobot();

	waitForStart();

	ClearTimer(T1);

	short firstMove = 1;
	short liftUp = 1;
	short secondMove = 1;
	short liftDown = 1;
	short firstTurn = 1;
	short thirdMove = 1;

	resetEncoders();
	while (firstMove == 1 || liftUp == 1){
		if (nMotorEncoder[Left] < 19*in){
			move(-80);
		}
		else{
			move(0);
			firstMove = 0;
		}
		if(time1[T1] < liftUpTime){
			liftUp = 1;
		}
		else{
			liftUp = 0;
			ClearTimer(T1);
		}
		if(liftUp == 1){
			motor[Lift1] = 100;
			motor[Lift2] = 100;
		}
		else{
			motor[Lift1] = 0;
			motor[Lift2] = 0;
		}
	}

	servo[bucket] = 130;
	wait1Msec(1000);
	servo[bucket] = 90;
	wait1Msec(2500);
	servo[bucket] = 130;
	wait1Msec(500);

	wait1Msec(250);
	resetEncoders();
	while(secondMove == 1 || liftDown == 1){
		if(nMotorEncoder[Left] < 20*in){
			move(-80);
		}
		else{
			move(0);
			secondMove = 0;
		}
		if(time1[T1] < liftDownTime){
			liftDown = 1;
		}
		else{
			liftDown = 0;
		}
		if(liftDown == 1){
			motor[Lift1] = -100;
			motor[Lift2] = -100;
		}
		if(liftDown == 0){
			motor[Lift1] = 0;
			motor[Lift2] = 0;
		}

	}
	resetEncoders();
	wait1Msec(250);
	while(firstTurn == 1){
		if(nMotorEncoder[Left] < 9*in){
			turn(100);
		}
		else{
			move(0);
			firstTurn = 0;
		}
	}
	wait1Msec(250);
	resetEncoders();
	while(thirdMove == 1){
		if(nMotorEncoder[Left] < 20*in){
			move(-100);
		}
		else{
			move(0);
			thirdMove = 0;
		}
	}
	move(0);
}
