#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S3,     infrared,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     touch,          sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     Left,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Right,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     Lift1,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     Lift2,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     Sweep,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     Flag,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    bucket,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    pin,                  tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Somebody's going to read our comments at some point and wonder what the hell we even did at these meetings...
//I, for one, am currently eating Doritos. (This is Zach, not Daniel)
//Seraphina is not glaring at her phone; she is on Snapchat.

//version 5.0.0 alpha

#include "JoystickDriver.c"

void setMovementPower_normal(int power, int turn){
	//int over100 = 0;
	//if (-power - turn < -100){
	//	(-power - turn)
	motor[Left] = power + turn;
	motor[Right] = power - turn;
}

int correctInputs(int input){
	if (abs(input) < 30)
		input = 0;
	return input;
}

void initializeRobot(){
	servo[bucket] = 135;
  setMovementPower_normal(0,0);
  servo[pin] = 0;
}

task main()
{
	initializeRobot();
while(SensorValue[touch] == false)
	setMovementPower_normal(25, 0);
setMovementPower_normal(0,0);






}
